POST http://localhost:3030/api/v1/register
Content-Type: application/json

{
  "username": "Tín Nguyễn",
  "email": "admin@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3030/api/v1/register
Content-Type: application/json

{
  "username": "",
  "email": "admin@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3030/api/v1/login
Content-Type: application/json

{
  "user": "admin@gmail.com",
  "password": "123456"
}

###
POST http://localhost:3030/api/v1/login
Content-Type: application/json

{
  "user": "Tín Nguyễn",
  "password": "123456"
}

###
POST http://localhost:3030/api/v1/refreshToken
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlTDrW4gTmd1eeG7hW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYyOTIwMDEyZTFkYTVhZGYxZDZkOGJiZSIsImlhdCI6MTY1Mzc1MzY5NywiZXhwIjoxNjU2MzQ1Njk3fQ.1WDvbaAQIDih3wANGK_aOBRqkfTa8FkPvm-iCLkf9yo"
}

###
POST http://localhost:3030/api/v1/logout
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlTDrW4gTmd1eeG7hW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTY1MzU1OTk5NywiZXhwIjoxNjUzNTYzNTk3fQ.T7J2RycaWZXKc7kKSvin3tJ9FaHFOhZt42ypF53_Qlk

###
POST http://localhost:3030/api/v1/test
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlTDrW4gTmd1eeG7hW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYyOTIwMDEyZTFkYTVhZGYxZDZkOGJiZSIsImlhdCI6MTY1Mzc1MzY5NywiZXhwIjoxNjUzNzU3Mjk3fQ.WHfJavkHYo2_MS0fuWf_6cbt5HxZJO4rO1jb13NiA5Q

###
POST http://localhost:3030/api/v1/addTopic
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlTDrW4gTmd1eeG7hW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYyOTIwMDEyZTFkYTVhZGYxZDZkOGJiZSIsImlhdCI6MTY1MzgxMDQwMywiZXhwIjoxNjUzODE0MDAzfQ.epwSCQt7lzG4eXkpAINBa6ZMfTeVRZ_sBddQKQVno8A

{
  "title" : "topic1fdsfds" 
}

###
GET http://localhost:3030/api/v1/getAllTopic
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlTDrW4gTmd1eeG7hW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYyOTIwMDEyZTFkYTVhZGYxZDZkOGJiZSIsImlhdCI6MTY1MzgxMDQwMywiZXhwIjoxNjUzODE0MDAzfQ.epwSCQt7lzG4eXkpAINBa6ZMfTeVRZ_sBddQKQVno8A

{
  "title" : "topic1" 
}

###
DELETE http://localhost:3030/api/v1/topic/629494da9acf808bfc870b82
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5jdGlucyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcklkIjoiNjI5MjAwMTJlMWRhNWFkZjFkNmQ4YmJlIiwiaWF0IjoxNjUzOTA0Njc1LCJleHAiOjE2NTM5MDgyNzV9.DFAXDZsT2nlQo8x8_AoKZ0JR9TfYcjzwE3txiXmQI6g

###
GET http://localhost:3030/api/v1/topic/62933416ba8c6cf7cb13641e/getVocab
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlTDrW4gTmd1eeG7hW4iLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjYyOTIwMDEyZTFkYTVhZGYxZDZkOGJiZSIsImlhdCI6MTY1MzgyMTE4OSwiZXhwIjoxNjUzODI0Nzg5fQ.T6jrekUZIqgo_PHWYDEwhpqYDv_XidjOMC1NBDnohE0

###
PUT http://localhost:3030/api/v1/vocab/6294c676e165867b2d8f49dc/changeFavorite
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5jdGlucyIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwidXNlcklkIjoiNjI5MjAwMTJlMWRhNWFkZjFkNmQ4YmJlIiwiaWF0IjoxNjUzOTE4NTQ3LCJleHAiOjE2NTM5MjIxNDd9.YXg9taKa_0A7DCaUgGqq8YLEPozGG0LMkD8iMfDR-88
